on: [push, pull_request]
name: Test
jobs:
  test:
    name: Test on ruby ${{ matrix.ruby_version }} with options - ${{ toJson(matrix.options) }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest, ruby_version: "3.0" }
          - { os: ubuntu-latest, ruby_version: "3.3" }
          - { os: ubuntu-latest, ruby_version: "jruby-9.4" }
    steps:
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.190.0
        with:
          bundler: 1
          ruby-version: ${{ matrix.ruby_version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          gem install bundler:2.3.7
          bundle install --jobs 4 --retry 3
          bundle exec rspec
