name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  setup:
    name: Tests
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Lint all packages
      run: |
        make docker-lint
